name: snowtargetminigame
version: "${version}"
main: com.spectrasonic.snowtargetminigame.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    defreeze:
        description: Main command for the plugin
        aliases: [st, df]
        permission: defreeze.main
permissions:
    defreeze.main:
        description: Main permission for the plugin
        default: op
